apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ys4fkh1f4-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ys4fkh1f4-go 
  name: ys4fkh1f4-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ys4fkh1f4-go 
